---

- hosts: master
  become: yes
  gather_facts: no

  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command > token.sh

    - name: copy token to my tmp
      fetch:
        src: /home/cloud-user/token.sh
        dest: /home/danya/skb/

- hosts: workers
  become: yes
  gather_facts: no

  tasks:
    - name: copy token to worker node use scp
      copy:
        src: /home/danya/skb/node0-master/home/cloud-user/token.sh
        dest: /home/cloud-user/
        mode: '0755'

    - name: join cluster
      shell: ./token.sh
